<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="7" hostname="LAPTOP-HTB7FUT0" failures="1" tests="1" name="Default test" time="17.733" errors="0" timestamp="2023-12-15T11:35:56 IST">
  <testcase classname="com.openCart.testCases.Register" name="TC_RF_009" time="11.9">
    <failure type="java.lang.AssertionError" message="Validation of  E-Mail Address is already registered! messaged Failed">
      <![CDATA[java.lang.AssertionError: Validation of  E-Mail Address is already registered! messaged Failed
at org.testng.Assert.fail(Assert.java:111)
at com.openCart.testCases.Register.TC_RF_009(Register.java:203)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_RF_009 -->
  <testcase classname="com.openCart.testCases.Register" name="TC_RF_005" time="0.0">
    <ignored/>
  </testcase> <!-- TC_RF_005 -->
  <testcase classname="com.openCart.testCases.Register" name="TC_RF_006" time="0.0">
    <ignored/>
  </testcase> <!-- TC_RF_006 -->
  <testcase classname="com.openCart.testCases.Register" name="TC_RF_007" time="0.0">
    <ignored/>
  </testcase> <!-- TC_RF_007 -->
  <testcase classname="com.openCart.testCases.Register" name="TC_RF_008" time="0.0">
    <ignored/>
  </testcase> <!-- TC_RF_008 -->
  <testcase classname="com.openCart.testCases.Register" name="TC_RF_001" time="0.0">
    <ignored/>
  </testcase> <!-- TC_RF_001 -->
  <testcase classname="com.openCart.testCases.Register" name="TC_RF_003" time="0.0">
    <ignored/>
  </testcase> <!-- TC_RF_003 -->
  <testcase classname="com.openCart.testCases.Register" name="TC_RF_004" time="0.0">
    <ignored/>
  </testcase> <!-- TC_RF_004 -->
</testsuite> <!-- Default test -->
